<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-04-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=200)),
                ('checkpoint', models.CharField(max_length=10)),
                ('direction', models.PositiveIntegerField()),
                ('detectedTime', models.DateTimeField()),
            ],
        ),
    ]
=======
# Generated by Django 4.0.4 on 2022-04-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=200)),
                ('checkpoint', models.CharField(max_length=10)),
                ('direction', models.PositiveIntegerField()),
                ('detectedTime', models.DateTimeField()),
            ],
        ),
    ]
>>>>>>> 619fc9f (updated web portal.)
